# Generated by Django 3.0.2 on 2020-03-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name_on_card',
            field=models.CharField(max_length=50, null=True, verbose_name='Name on Card'),
        ),
    ]
