# Generated by Django 3.0.2 on 2020-02-29 06:36

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200227_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('state', models.CharField(default='FL', max_length=128, verbose_name='State')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zipcode')),
            ],
            options={
                'verbose_name_plural': 'ShippingAddress',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('state', models.CharField(default='FL', max_length=128, verbose_name='State')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zipcode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='credit_card',
            field=models.ManyToManyField(related_name='users', to='users.ShippingAddress'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shipping_address',
            field=models.ManyToManyField(related_name='user', to='users.ShippingAddress'),
        ),
    ]
