# Generated by Django 3.0.2 on 2020-02-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200229_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payment'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='credit_card',
            field=models.ManyToManyField(related_name='user', to='users.Payment'),
        ),
    ]
