# Generated by Django 3.0.2 on 2020-03-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200309_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city_area',
        ),
    ]
