# Generated by Django 3.0.2 on 2020-03-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_address_city_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'ShipAddress'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country_code',
            field=models.CharField(blank=True, choices=[('US', 'United States of America')], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
    ]
