# Generated by Django 3.0.2 on 2020-02-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20200227_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(default='test'),
        ),
    ]
