# Generated by Django 3.0.2 on 2020-02-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_auto_20200227_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
